name: usstockminimemo
description: Flutter USA stocks mini memo application.

publish_to: 'none'

# android
# version: 1.1.3+8

# iPhone
version: 1.1.3+4

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.0
  path: ^1.8.2
  provider: ^6.0.5
  sqflite: ^2.2.2
  intl: ^0.18.0
  google_mobile_ads: ^2.3.0
  shared_preferences: ^2.0.18
  package_info_plus: ^3.0.3
  flutter_dotenv: ^5.0.2
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  drift_dev: ^2.2.0+1
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/icons/icon_android.png'
  image_path_ios: 'assets/icons/icon_ios.png'

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env # .envの設定を追加.